### ISSUE TITLE
Building woes? :(

### ISSUE THREAD

**Issue by toddmay222** [Ronny-dev/MSDK_AI#1]
First off... THank you for sharing this resource!

I have tried two versions of Android Studio and countless Gradle versions with no luck for a successful build.

Could you please share the details of:
What ver JDK
What ver gradle

Thanks

**Comment by Ronny-dev** [comment]
Hello
Can you tell me what is wrong at the moment? Maybe it's not a compiler build problem.

**Comment by toddmay222** [comment]
Ronny,
Thanks for the reply.
First AttemptUsed AStudio 4.2.2 - Riddled with issues.
Second AttemptUsed AStudio Flamingo 2022.2.1Got it running on android device - But no video.
Issues I saw were:1 - Gradle file requires namespace.2 - Took me a long time to figure out what combination of JDK I needed and what Gradle version.3 - Even after I got it to build and install on device... The MainActivity can not find import com.geoai.msdk_ai.ml.Model
Other minor concerns were:1 - We have to register on DJI for API Key.  When we do that, we have to enter the name of the program like com.ronnys.amazingapp
2 - The manifest file holds the API key... But it isn't clear if we have to enter com.ronnys.amazingapp there (the same as we signed up for key) or use the name com.dji.sdk.API_KEY
SummaryFor you Android veterans this may be simple stuff.   But for us guys coming from other languages there is a learning curve here.
If you could share some more of your wisdom regarding setup within the README docs... it would save us non-daily android folks a great deal of time. :)
I appreciate you Ronny!   Best wishes to team and family.
Todd


    On Saturday, May 6, 2023 at 01:57:46 AM EDT, Ronny ***@***.***> wrote:  
 
 


Hello
Can you tell me what is wrong at the moment? Maybe it's not a compiler build problem.

**Comment by Ronny-dev** [comment]
I am very sorry that I was on leave yesterday and did not reply to your message in time.
I have tried to use other android studio and have not found the problem you mentioned.
Next I will list my computer environment, I hope it will be helpful to you:
Android Studio Version: 2021.3.1 RC 1
Gradle Version: gradle-7.0.2
-------------------------------------------------
Model is a model file stored in "app/src/main/ml", You can delete it! I found some examples on the Internet:
https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#0
-------------------------------------------------
I have filled in the Key of DJI correctly in the AndroidManifest. You don't need to care about the key.
If you want to learn about the DJI MSDK-related features, the following links may help:
https://developer.dji.com/doc/mobile-sdk-tutorial/en/

I hope my answer can help you Solve this problem.

by the way, what should I call you?

**Comment by Ronny-dev** [comment]
There should be wrong screenshots, if possible, you can send the screenshots, so that I can better help you solve the problem

**Comment by toddmay222** [comment]
Roony,
Todd here... Sorry for the slow response.   Busy life. LOL
I encountered MANY issues with the DJI MSDK on M30T.   I finally got over most of those by downgrading my android studio to Bumblebee 2021.1.1.
BUT.. The place I am hung up on now is... Around line 276 of MainActivity if (aa)
I see that you are setting this to false once it gets inside the block.BMP is made and sent to tensorflow for processing.But... Then the code is never executed again.If one sets AA to true after the bmp is processed to keep the block alive... it will crash.
I am new to android development.  Mostly a nodeJS guys and old school Perl guru.
Also... Lastly... In your example and experiencec with DJI MSDK.   Is it possible to:1- Capture the video stream from drone.2 - Perform backend processing on images.3 - Return bounding boxes on the video feed.
The end goal is:1- Allow DJI Pilot2 to run.2 - Have backend process that is montioring video passively.3 - Backend process injects bounding boxes and labels onto video.4 - User realizes the end result INSIDE DJI Pilot2?
Is my goal achievable my friend... Or am I just wasting time here and need to focus on OSDK and do my work at the FFMPEG layer using onboard computer on aicraft?
Thanks my friend.
Todd

    On Monday, May 8, 2023 at 12:13:54 AM EDT, Ronny ***@***.***> wrote:  
 
 


There should be wrong screenshots, if possible, you can send the screenshots, so that I can better help you solve the problem

**Comment by toddmay222** [comment]
Ronny,
FYI... model.close() was causing exception - Although documentation indicates to close it, there were cases where the exception would indicate the model was already closed.
Attempts to ignore that exception with try/catch failed.
Commented model.close() and monitored performance of live stream... No issues were seen with CPU consumption and/or memory leaks.

Your code sample got me far enough along to get moving... I appreciate you.


    On Monday, May 8, 2023 at 12:12:09 AM EDT, Ronny ***@***.***> wrote:  
 
 


I am very sorry that I was on leave yesterday and did not reply to your message in time.
I have tried to use other android studio and have not found the problem you mentioned.
Next I will list my computer environment, I hope it will be helpful to you:
Android Studio Version: 2021.3.1 RC 1
Gradle Version: gradle-7.0.2

Model is a model file stored in "app/src/main/ml", You can delete it! I found some examples on the Internet:
https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#0

I have filled in the Key of DJI correctly in the AndroidManifest. You don't need to care about the key.
If you want to learn about the DJI MSDK-related features, the following links may help:
https://developer.dji.com/doc/mobile-sdk-tutorial/en/

I hope my answer can help you Solve this problem.

by the way, what should I call you?

**Comment by Ronny-dev** [comment]
Todd,
I am very sorry that the exception on the sample code made you feel confused, The sample is pieced from parts of the code extracted from my project.
Let me respond to your questions:

	Q1: Capture the video stream from drone.
		A:By MSDK, You can certainly take the raw video stream and do something about it.

	Q2: Perform backend processing on images.
		A:I'm not sure what you want to do with the image, If you need to 'AI Process',You need to figure out how to combine with AI such as tensorflow or yolo. If you just want analyze BMP, you can implement opencv in java do what you want.

	Q3: Return bounding boxes on the video feed.
		A:You can learn the sample program.

	Q4:  model.close() was causing exception
		A:I gave it a try, it cause an exception; But this is an example program. I try to extract the methods from addYuvDataListener into click, and the code will not have an exception. Of course, you can parse out the coordinates of the video frame to draw, I believe should be able to meet your needs to Q3.

	Q5: goal is: 1- Allow DJI Pilot2 to run.2 - Have backend process that is montioring video passively.3 - Backend process injects bounding boxes and labels onto video.4 - User realizes the end result INSIDE DJI Pilot2?
		A:From your needs, I think you should look into PSDK; If you have MSDK running on your device, you will no longer be able to run dji pilot. You can download dji msdk sample code from [developer.dji.com] to try it.

 best wishes.
 Ronny

**Comment by toddmay222** [comment]
Ronny,
I appreciate your wisdom and willingness to share.
Yes... That was my concern from a MSDK standpoint... I was hopeful to be able to backend process the video using yolo or tensorflow and have pilot2 display the bounding boxes.
I wish DJI would allow primary or secondary video streams to allow a "man in the middle".   But it is what it is.
Your willingness to share your creation with others sparked enough brain cells on my end to make progress and learn.
And at the end of the day... That is what it's all about.
I appreciate your responses and willingness to post public code.
Take care Ronny and best wishes to team and family.
Todd


Sent from Yahoo Mail on Android 
 
  On Sun, May 14, 2023 at 22:38, ***@***.***> wrote:   


Todd,
I am very sorry that the exception on the sample code made you feel confused, The sample is pieced from parts of the code extracted from my project.
Let me respond to your questions:
Q1: Capture the video stream from drone.
	A:By MSDK, You can certainly take the raw video stream and do something about it.

Q2: Perform backend processing on images.
	A:I'm not sure what you want to do with the image, If you need to 'AI Process',You need to figure out how to combine with AI such as tensorflow or yolo. If you just want analyze BMP, you can implement opencv in java do what you want.

Q3: Return bounding boxes on the video feed.
	A:You can learn the sample program.

Q4:  model.close() was causing exception
	A:I gave it a try, it cause an exception; But this is an example program. I try to extract the methods from addYuvDataListener into click, and the code will not have an exception. Of course, you can parse out the coordinates of the video frame to draw, I believe should be able to meet your needs to Q3.

Q5: goal is: 1- Allow DJI Pilot2 to run.2 - Have backend process that is montioring video passively.3 - Backend process injects bounding boxes and labels onto video.4 - User realizes the end result INSIDE DJI Pilot2?
	A:From your needs, I think you should look into PSDK; If you have MSDK running on your device, you will no longer be able to run dji pilot. You can download dji msdk sample code from [developer.dji.com] to try it.

best wishes.
Ronny
